import {useEffect,useState} from "react";
import {BookOpen,Brain,CheckCircle2,ChevronRight,FileText,Image,Library,Plus,Settings,ShieldCheck,Sparkles,WandSparkles} from "lucide-react";
const API="http://127.0.0.1:8000";
type Project={id:string;name:string;book_type:string;language:string;status:string;progress:number};
const types=[["childrens","🎨","Livro infantil","Histórias, personagens e ilustrações"],["fiction","📖","Romance / Ficção","Livros longos com capítulos"],["educational","📚","Educativo","Conteúdo didático e aprendizagem"],["workbook","📝","Workbook","Exercícios, atividades e respostas"],["journal","📓","Diário / Journal","Diários, planners e registros"],["cookbook","🍳","Livro de receitas","Receitas organizadas e ilustradas"],["study","🧠","Estudo / Apostila","Resumos, questões e material de estudo"],["custom","⚙️","Personalizado","Começar um projeto do zero"]];
export default function App(){
 const [projects,setProjects]=useState<Project[]>([]),[name,setName]=useState(""),[type,setType]=useState("childrens"),[language,setLanguage]=useState("pt-BR"),[loading,setLoading]=useState(false),[view,setView]=useState<"home"|"new"|"projects">("home"),[system,setSystem]=useState<any>(null);
 async function load(){try{const [p,d]=await Promise.all([fetch(API+"/api/projects"),fetch(API+"/api/doctor")]);setProjects(await p.json());setSystem(await d.json())}catch{}}
 useEffect(()=>{load()},[]);
 async function create(){if(!name.trim())return;setLoading(true);try{const r=await fetch(API+"/api/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,book_type:type,language})});const p=await r.json();setProjects(x=>[p,...x]);setName("");setView("projects")}finally{setLoading(false)}}
 return <div className="app"><aside className="sidebar"><div className="brand"><div className="logo">K</div><div><b>KDP AI</b><span>FACTORY</span></div></div><nav><button className={view==="home"?"active":""} onClick={()=>setView("home")}><Sparkles/>Início</button><button className={view==="projects"?"active":""} onClick={()=>setView("projects")}><Library/>Meus projetos</button><button onClick={()=>setView("new")}><Plus/>Novo livro</button></nav><div className="sideBottom"><div className="miniStatus"><span className="dot"/> Sistema local<br/><small>{system?"online":"conectando..."}</small></div><button><Settings/>Configurações</button></div></aside><main><header><div><span className="eyebrow">LOCAL-FIRST • OPEN AI STACK</span><h1>{view==="new"?"Criar novo livro":view==="projects"?"Meus projetos":"Sua fábrica editorial com IA"}</h1></div><button className="outline" onClick={()=>setView("new")}><Plus/> Novo projeto</button></header>
{view==="home"&&<><section className="hero"><div><div className="pill"><WandSparkles/> IA local • sem créditos obrigatórios</div><h2>Transforme uma ideia em um <em>livro completo.</em></h2><p>Escreva, ilustre, diagrama, valide e prepare seus livros para KDP em um único ambiente.</p><button className="primary" onClick={()=>setView("new")}>Começar um livro <ChevronRight/></button></div><div className="heroArt"><BookOpen size={110}/><Sparkles className="spark s1"/><Sparkles className="spark s2"/></div></section><section className="grid"><Feature icon={<Brain/>} title="IA local" text="Ollama e outros modelos sem depender de API paga."/><Feature icon={<Image/>} title="Imagens" text="Geração local com workflows do ComfyUI."/><Feature icon={<ShieldCheck/>} title="Validação KDP" text="Prepare arquivos seguindo os requisitos do projeto."/><Feature icon={<FileText/>} title="Importação" text="Base para transformar seus próprios materiais em livros."/></section><section className="section"><div className="sectionTitle"><h3>Projetos recentes</h3><button onClick={()=>setView("projects")}>Ver todos</button></div><Projects items={projects.slice(0,4)}/></section></>}
{view==="projects"&&<section className="section page"><div className="sectionTitle"><h3>{projects.length?projects.length+" projeto(s)":"Nenhum projeto ainda"}</h3><button className="primary small" onClick={()=>setView("new")}><Plus/> Criar livro</button></div><Projects items={projects}/></section>}
{view==="new"&&<section className="creator"><div className="step"><span>01</span><div><b>Escolha o tipo de livro</b><small>Você poderá alterar detalhes depois.</small></div></div><div className="typeGrid">{types.map(t=><button className={type===t[0]?"type selected":"type"} onClick={()=>setType(t[0])} key={t[0]}><span className="typeIcon">{t[1]}</span><strong>{t[2]}</strong><small>{t[3]}</small></button>)}</div><div className="formCard"><div><label>Nome do projeto</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: A Floresta Encantada"/></div><div><label>Idioma principal</label><select value={language} onChange={e=>setLanguage(e.target.value)}><option value="pt-BR">Português (Brasil)</option><option value="en-US">English (US)</option><option value="es-ES">Español</option><option value="fr-FR">Français</option><option value="de-DE">Deutsch</option></select></div></div><div className="actions"><button className="outline" onClick={()=>setView("home")}>Cancelar</button><button className="primary" disabled={!name.trim()||loading} onClick={create}>{loading?"Criando...":"Criar projeto"}<ChevronRight/></button></div></section>}</main></div>
}
function Feature({icon,title,text}:{icon:any;title:string;text:string}){return <div className="feature">{icon}<div><b>{title}</b><p>{text}</p></div></div>}
function Projects({items}:{items:Project[]}){if(!items.length)return <div className="empty"><CheckCircle2/><b>Seu primeiro livro começa aqui.</b><span>Crie um projeto e o Factory cuidará do restante.</span></div>;return <div className="projects">{items.map(p=><div className="project" key={p.id}><div className="projectIcon">📘</div><div className="projectInfo"><b>{p.name}</b><span>{p.book_type} • {p.language}</span><div className="bar"><i style={{width:p.progress+"%"}}/></div></div><strong>{p.progress}%</strong></div>)}</div>}