import {useEffect,useMemo,useState} from "react";
import {Activity,BookOpen,Brain,CheckCircle2,ChevronRight,FileText,Image as ImageIcon,Library,Plus,Settings,ShieldCheck,Sparkles,Video,WandSparkles,Trash2,Play,RefreshCw,Cloud,Save,Users,LogIn,LogOut,Copy,Printer,ArrowUp,ArrowDown} from "lucide-react";

const API="";
type Project={id:string;name:string;book_type:string;language:string;status:string;progress:number;updated_at?:string};
type Provider={id:string;name:string;kind:string;base_url?:string;endpoint?:string;model?:string;priority?:number;key_configured?:boolean};
const types=[["childrens","🎨","Livro infantil","Histórias, personagens e ilustrações"],["fiction","📖","Romance / Ficção","Livros longos com capítulos"],["educational","📚","Educativo","Conteúdo didático"],["workbook","📝","Workbook","Exercícios e atividades"],["journal","📓","Diário / Journal","Diários e planners"],["cookbook","🍳","Livro de receitas","Receitas e conteúdo culinário"],["study","🧠","Estudo / Apostila","Resumos e questões"],["coloring","🖍️","Colorir / Atividades","Páginas para colorir"],["poetry","✒️","Poesia","Poemas e coletâneas"],["notebook","📒","Caderno","Miolo simples"],["custom","⚙️","Personalizado","Projeto livre"]];
const languages=[["pt-BR","Português (Brasil)"],["en-US","English (US)"],["en-GB","English (UK)"],["es-ES","Español"],["fr-FR","Français"],["de-DE","Deutsch"],["it-IT","Italiano"],["pt-PT","Português (Portugal)"],["ja-JP","日本語"],["ko-KR","한국어"],["zh-CN","简体中文"],["zh-TW","繁體中文"],["hi-IN","हिन्दी"],["ar-SA","العربية"],["nl-NL","Nederlands"],["pl-PL","Polski"],["tr-TR","Türkçe"],["ru-RU","Русский"]];
const stages=["brief","outline","manuscript","revision","assets","layout","cover","validation","export"];

export default function App(){
 const [projects,setProjects]=useState<Project[]>([]),[name,setName]=useState(""),[type,setType]=useState("childrens"),[language,setLanguage]=useState("pt-BR"),[subject,setSubject]=useState(""),[edition,setEdition]=useState("print"),[author,setAuthor]=useState(""),[coverMode,setCoverMode]=useState("images_only"),[contentMode,setContentMode]=useState("text_and_images"),[resolution,setResolution]=useState("kdp_300dpi"),[publicationFormat,setPublicationFormat]=useState("paperback"),[printMode,setPrintMode]=useState("kdp"),[trimSize,setTrimSize]=useState("6x9"),[aiBrief,setAiBrief]=useState(""),[aiScript,setAiScript]=useState(""),[loading,setLoading]=useState(false),[view,setView]=useState("home"),[system,setSystem]=useState<any>(null),[license,setLicense]=useState<any>(null),[selected,setSelected]=useState<Project|null>(null),[aiPrompt,setAiPrompt]=useState(""),[aiResult,setAiResult]=useState("");
 const [sessionRecovered,setSessionRecovered]=useState(false);
 const [photoDraft,setPhotoDraft]=useState<File[]>([]),[photoCover,setPhotoCover]=useState<string|null>(null),[photoBack,setPhotoBack]=useState<string|null>(null),[photoInterior,setPhotoInterior]=useState<string[]>([]),[printDraft,setPrintDraft]=useState<File[]>([]),[printCover,setPrintCover]=useState<string|null>(null),[printBack,setPrintBack]=useState<string|null>(null),[printInterior,setPrintInterior]=useState<string[]>([]);

 async function load(){
  try{
   const [p,d,l]=await Promise.all([fetch(API+"/api/projects"),fetch(API+"/api/doctor"),fetch(API+"/api/license")]);
   const ps=await p.json(); setProjects(ps); setSystem(await d.json()); setLicense(await l.json());
   const last=localStorage.getItem("kdp:lastProject");
   if(last){const found=ps.find((x:Project)=>x.id===last);if(found){setSelected(found);setSessionRecovered(true)}}
  }catch{}
 }
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(selected?.id)localStorage.setItem("kdp:lastProject",selected.id)},[selected?.id]);
 useEffect(()=>{if(!selected?.id)return;const t=setTimeout(()=>{fetch(API+"/api/projects/"+selected.id+"/checkpoint",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({stage:"workspace_autosave",state:{aiPrompt,view:"workspace"}})}).catch(()=>{})},1000);return()=>clearTimeout(t)},[aiPrompt,selected?.id]);
 async function create(){
  if(!name.trim())return;setLoading(true);
  try{
   const r=await fetch(API+"/api/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,book_type:type,language,subject,edition:publicationFormat,author,content_mode:contentMode,resolution,publication_format:publicationFormat,print_mode:printMode,ai_brief:aiBrief,ai_script:aiScript,trim_size:trimSize})});
   const p=await r.json();
   if(!r.ok){alert(p.detail||"Ative a licença para continuar.");setView("system");return}
   if(printDraft.length){
    const fd=new FormData();printDraft.forEach(f=>fd.append("files",f));
    const ir=await fetch(API+"/api/projects/"+p.id+"/print-files",{method:"POST",body:fd});
    const id=await ir.json();
    if(!ir.ok)throw new Error(id.detail||"O projeto foi criado, mas não foi possível importar os PDFs/arquivos de impressão.");
    const pids=(id.files||[]).map((x:any)=>x.id);
    const roleRequests:any[]=[];
    if(printCover!==null&&pids[Number(printCover)])roleRequests.push({id:pids[Number(printCover)],role:"cover"});
    if(printBack!==null&&pids[Number(printBack)])roleRequests.push({id:pids[Number(printBack)],role:"back_cover"});
    printInterior.forEach(k=>{const rid=pids[Number(k)];if(rid)roleRequests.push({id:rid,role:"interior"})});
    for(const role of roleRequests){
      const rr=await fetch(API+"/api/projects/"+p.id+"/print-files/role",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(role)});
      if(!rr.ok)throw new Error("Os PDFs foram importados, mas não foi possível salvar as funções.");
    }
   }
   if(photoDraft.length){
    const fd=new FormData();photoDraft.forEach(f=>fd.append("files",f));
    const pr=await fetch(API+"/api/projects/"+p.id+"/photos",{method:"POST",body:fd});
    const pd=await pr.json();
    if(!pr.ok)throw new Error(pd.detail||"O projeto foi criado, mas não foi possível importar as fotos.");
    const ids=(pd.added||[]).map((x:any)=>x.id);
    const byName=(file:File,i:number)=>ids[i]||null;
    const coverId=photoCover!==null?byName(photoDraft[Number(photoCover)],Number(photoCover)):null;
    const backId=photoBack!==null?byName(photoDraft[Number(photoBack)],Number(photoBack)):null;
    const interiorIds=photoInterior.map(k=>byName(photoDraft[Number(k)],Number(k))).filter(Boolean);
    const rr=await fetch(API+"/api/projects/"+p.id+"/photos",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({cover:coverId,back_cover:backId,interior:interiorIds})});
    if(!rr.ok){const rd=await rr.json().catch(()=>({}));throw new Error(rd.detail||"As fotos foram importadas, mas não foi possível salvar suas funções.")}
   }
   setProjects(x=>[p,...x]);setName("");setPhotoDraft([]);setPhotoCover(null);setPhotoBack(null);setPhotoInterior([]);setPrintDraft([]);setPrintCover(null);setPrintBack(null);setPrintInterior([]);setSelected(p);setView("workspace");
  }catch(e){alert(e instanceof Error?e.message:"Não foi possível criar o projeto.");}
  finally{setLoading(false)}
 }
 async function generate(){if(!aiPrompt||!selected)return;setAiResult("Gerando...");try{const r=await fetch(API+"/api/ai/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:aiPrompt})});const d=await r.json();setAiResult(d.text||d.detail||"Sem resposta")}catch{setAiResult("Não foi possível conectar aos provedores configurados.")}}
 function openProject(p:Project){setSelected(p);setView("workspace");setSessionRecovered(false)}
 return <div className="app"><aside className="sidebar"><div className="brand"><div className="logo">K</div><div><b>KDP AI</b><span>FACTORY</span></div></div><nav>
  <button className={view==="home"?"active":""} onClick={()=>setView("home")}><Sparkles/>Início</button>
  <button className={view==="projects"?"active":""} onClick={()=>setView("projects")}><Library/>Meus projetos</button>
  <button className={view==="new"?"active":""} onClick={()=>setView("new")}><Plus/>Novo livro</button>
  <button className={view==="workspace"?"active":""} onClick={()=>setView(selected?"workspace":"projects")}><BookOpen/>Produção</button>
  <button className={view==="video"?"active":""} onClick={()=>setView("video")}><Video/>Vídeos sociais</button>
  <button className={view==="affiliate"?"active":""} onClick={()=>setView("affiliate")}><Users/>Afiliados</button><button className={view==="print"?"active":""} onClick={()=>setView(selected?"print":"projects")}><Printer/>Impressão</button>
  <button className={view==="system"?"active":""} onClick={()=>setView("system")}><Activity/>Sistema / IA</button>
 </nav><div className="sideBottom"><div className="miniStatus"><span className="dot"/>{system?"Sistema online":"Conectando..."}<br/><small>Cloud-first • projetos salvos automaticamente</small></div><button onClick={()=>setView("system")}><Settings/>Configurações</button></div></aside>
 <main><header><div><span className="eyebrow">CLOUD-FIRST • WINDOWS + LINUX + WEB</span><h1>{view==="new"?"Criar novo livro":view==="projects"?"Meus projetos":view==="workspace"?"Área de produção":view==="video"?"Vídeos para redes sociais":view==="affiliate"?"Programa de afiliados":view==="print"?"Preparar para impressão":view==="system"?"Sistema e modelos":"Sua fábrica editorial com IA"}</h1></div><button className="outline" onClick={()=>setView("new")}><Plus/> Novo projeto</button></header>
 {sessionRecovered&&view==="home"&&<div className="recover"><RefreshCw size={18}/><div><b>Sessão recuperada</b><span>O último projeto aberto continua salvo: {selected?.name}</span></div><button className="primary small" onClick={()=>setView("workspace")}>Continuar</button></div>}
 {view==="home"&&<><section className="hero"><div><div className="pill"><Cloud/> IA remota • PC leve</div><h2>Transforme uma ideia em um <em>livro completo.</em></h2><p>Escreva, ilustre, diagrama, valide e prepare seus livros para KDP. As APIs ficam salvas no aplicativo e a IA pesada pode rodar na nuvem.</p><button className="primary" onClick={()=>setView("new")}>Começar um livro <ChevronRight/></button><div style={{marginTop:12,fontSize:13}}>{license?.licensed?"Licença vitalícia ativa":"Teste: "+(license?.free_books_remaining??1)+" livro gratuito disponível"}</div></div><div className="heroArt"><BookOpen size={110}/><Sparkles className="spark s1"/><Video className="spark s2"/></div></section>
 <section className="grid"><Feature icon={<Brain/>} title="Várias IAs" text="Cadastre quantos provedores quiser, inclusive APIs que fazem texto + imagem."/><Feature icon={<ImageIcon/>} title="Imagens" text="APIs externas, engine remoto ou geração local como fallback."/><Feature icon={<Video/>} title="Vídeo social" text="Gere vídeos promocionais a partir do livro criado."/><Feature icon={<ShieldCheck/>} title="Persistência" text="Projetos, APIs e checkpoints ficam salvos no computador."/></section>
 <section className="section"><div className="sectionTitle"><h3>Projetos recentes</h3><button onClick={()=>setView("projects")}>Ver todos</button></div><Projects items={projects.slice(0,4)} onOpen={openProject}/></section></>}
 {view==="projects"&&<section className="section page"><div className="sectionTitle"><h3>{projects.length?projects.length+" projeto(s)":"Nenhum projeto ainda"}</h3><button className="primary small" onClick={()=>setView("new")}><Plus/> Criar livro</button></div><Projects items={projects} onOpen={openProject}/></section>}
 {view==="new"&&<section className="creator">{license?.licensed||license?.free_books_remaining>0?null:<div className="formCard"><div><b>Teste gratuito encerrado</b><p>Ative a licença vitalícia para criar novos livros.</p></div><button className="primary" onClick={()=>setView("system")}>Ativar licença</button></div>}<div className="step"><span>01</span><div><b>Escolha o tipo de livro</b><small>O tipo orienta o fluxo editorial e a geração de conteúdo.</small></div></div><div className="typeGrid">{types.map(t=><button className={type===t[0]?"type selected":"type"} onClick={()=>setType(t[0])} key={t[0]}><span className="typeIcon">{t[1]}</span><strong>{t[2]}</strong><small>{t[3]}</small></button>)}</div><div className="formCard"><div><label>Assunto / tema do livro</label><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Ex.: dinossauros, receitas, romance policial"/><small>O assunto será usado no conteúdo, metadados e roteiro de divulgação.</small><label>Nome do projeto</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: A Floresta Encantada"/></div><div><label>Idioma do livro</label><select value={language} onChange={e=>setLanguage(e.target.value)}>{languages.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div></div><BookSettings author={author} setAuthor={setAuthor} coverMode={coverMode} setCoverMode={setCoverMode} contentMode={contentMode} setContentMode={setContentMode} resolution={resolution} setResolution={setResolution} publicationFormat={publicationFormat} setPublicationFormat={setPublicationFormat} printMode={printMode} trimSize={trimSize} setTrimSize={setTrimSize} setPrintMode={setPrintMode} aiBrief={aiBrief} setAiBrief={setAiBrief} aiScript={aiScript} setAiScript={setAiScript}/><PhotoDraft files={photoDraft} setFiles={setPhotoDraft} cover={photoCover} setCover={setPhotoCover} back={photoBack} setBack={setPhotoBack} interior={photoInterior} setInterior={setPhotoInterior} printFiles={printDraft} setPrintFiles={setPrintDraft} printCover={printCover} setPrintCover={setPrintCover} printBack={printBack} setPrintBack={setPrintBack} printInterior={printInterior} setPrintInterior={setPrintInterior}/><div className="actions"><button className="outline" onClick={()=>setView("home")}>Cancelar</button><button className="primary" disabled={!name.trim()||loading} onClick={create}>{loading?"Criando...":"Criar projeto"}<ChevronRight/></button></div></section>}
 {view==="workspace"&&<Workspace project={selected} onBack={()=>setView("projects")} onProjectUpdate={async(id)=>{try{const r=await fetch(API+"/api/projects/"+id);if(r.ok){const p=await r.json();setSelected(p);setProjects(xs=>xs.map(x=>x.id===p.id?p:x))}}catch{}}} aiPrompt={aiPrompt} setAiPrompt={setAiPrompt} aiResult={aiResult} generate={generate} goVideo={()=>setView("video")} goPrint={()=>setView(selected?"print":"projects")}/>}
 {view==="video"&&<VideoStudio projects={projects} project={selected} onSelect={p=>setSelected(p)} onBack={()=>setView(selected?"workspace":"projects")} onConfigure={()=>setView("system")}/>}
 {view==="affiliate"&&<AffiliatePanel/>}
 {view==="print"&&<PrintStudio project={selected} onBack={()=>setView(selected?"workspace":"projects")}/>}
 {view==="system"&&<System system={system} license={license} onActivated={load}/>}
 </main></div>
}


function BookSettings({author,setAuthor,coverMode,setCoverMode,contentMode,setContentMode,resolution,setResolution,publicationFormat,setPublicationFormat,printMode,setPrintMode,trimSize,setTrimSize,aiBrief,setAiBrief,aiScript,setAiScript}:{author:string;setAuthor:(v:string)=>void;coverMode:string;setCoverMode:(v:string)=>void;contentMode:string;setContentMode:(v:string)=>void;resolution:string;setResolution:(v:string)=>void;publicationFormat:string;setPublicationFormat:(v:string)=>void;printMode:string;setPrintMode:(v:string)=>void;trimSize:string;setTrimSize:(v:string)=>void;aiBrief:string;setAiBrief:(v:string)=>void;aiScript:string;setAiScript:(v:string)=>void}){
 const [tab,setTab]=useState("content");
 return <div className="section">
  <div className="sectionTitle"><div><h3>Configuração editorial e KDP</h3><p>Essas escolhas ficam gravadas no projeto e são usadas pelo fluxo de geração.</p></div></div>
  <div className="tabs">
   <button className={tab==="content"?"tab active":"tab"} onClick={()=>setTab("content")}>Conteúdo</button>
   <button className={tab==="format"?"tab active":"tab"} onClick={()=>setTab("format")}>Publicação e resolução</button>
   <button className={tab==="ai"?"tab active":"tab"} onClick={()=>setTab("ai")}>Comandos / roteiro para IA</button>
   <button className={tab==="author"?"tab active":"tab"} onClick={()=>setTab("author")}>Autor</button>
  </div>
  {tab==="content"&&<div className="formCard">
   <div><label>Como quer a capa?</label><select value={coverMode} onChange={e=>setCoverMode(e.target.value)}><option value="images_only">Somente imagens — uma imagem por página</option><option value="text_and_images">Imagens + texto na mesma página</option><option value="text_only">Somente texto</option></select><small>Define a composição da capa. A IA deverá respeitar essa escolha.</small><label>Como quer a parte de dentro?</label><select value={contentMode} onChange={e=>setContentMode(e.target.value)}><option value="images_only">Somente imagens — uma imagem por página</option><option value="text_and_images">Imagens + texto na mesma página</option><option value="text_only">Somente texto</option></select><small>Define a composição principal do miolo. A IA deverá respeitar essa escolha.</small></div>
   <div><label>Modo de impressão</label><select value={printMode} onChange={e=>{const v=e.target.value;setPrintMode(v);if(v==="independent_print")setPublicationFormat("independent_print");}}><option value="kdp">KDP Amazon</option><option value="independent_print">Impressão independente / gráfica</option></select><small>O modo independente permite trabalhar com medidas da gráfica.</small></div>
  </div>}
  {tab==="format"&&<div className="formCard">
   <div><label>Formato de publicação</label><select value={publicationFormat} onChange={e=>{const v=e.target.value;setPublicationFormat(v);if(v==="independent_print")setPrintMode("independent_print");else if(printMode==="independent_print")setPrintMode("kdp")}}>
    <option value="ebook_reflowable">eBook Kindle — layout dinâmico (reflowable)</option><option value="ebook_fixed">eBook Kindle — layout fixo</option><option value="ebook_fixed_popups">eBook Kindle — layout fixo com pop-ups de texto</option><option value="ebook_panel_view">eBook Kindle — layout fixo com painéis/quadros virtuais</option><option value="paperback">Livro impresso — capa comum</option><option value="hardcover">Livro impresso — capa dura</option><option value="paperback_ebook">Capa comum + eBook</option><option value="hardcover_ebook">Capa dura + eBook</option><option value="paperback_hardcover_ebook">Capa comum + capa dura + eBook</option><option value="independent_print">Impressão independente — gráfica</option>
   </select><small>Ao selecionar esta opção, o projeto entra automaticamente no modo de impressão independente/gráfica.</small></div>
   <div><label>Dimensões finais do livro (KDP)</label><select value={trimSize} onChange={e=>setTrimSize(e.target.value)}><option value="5x8">5 × 8 pol. (12,7 × 20,32 cm)</option><option value="5.06x7.81">5,06 × 7,81 pol. (12,85 × 19,84 cm)</option><option value="5.25x8">5,25 × 8 pol. (13,34 × 20,32 cm)</option><option value="5.5x8.5">5,5 × 8,5 pol. (13,97 × 21,59 cm)</option><option value="6x9">6 × 9 pol. (15,24 × 22,86 cm)</option><option value="6.14x9.21">6,14 × 9,21 pol. (15,6 × 23,39 cm)</option><option value="6.69x9.61">6,69 × 9,61 pol. (16,99 × 24,41 cm)</option><option value="7x10">7 × 10 pol. (17,78 × 25,4 cm)</option><option value="7.44x9.69">7,44 × 9,69 pol. (18,9 × 24,61 cm)</option><option value="7.5x9.25">7,5 × 9,25 pol. (19,05 × 23,5 cm)</option><option value="8x10">8 × 10 pol. (20,32 × 25,4 cm)</option><option value="8.25x6">8,25 × 6 pol. (20,96 × 15,24 cm)</option><option value="8.25x8.25">8,25 × 8,25 pol. (20,96 × 20,96 cm)</option><option value="8.5x8.5">8,5 × 8,5 pol. (21,59 × 21,59 cm)</option><option value="8.5x11">8,5 × 11 pol. (21,59 × 27,94 cm)</option><option value="8.27x11.69">8,27 × 11,69 pol. (21 × 29,7 cm)</option><option value="custom">Personalizado / gráfica</option></select><small>Lista baseada nas dimensões atuais publicadas pelo KDP para capa comum; capa dura possui um subconjunto próprio.</small><label>Resolução / qualidade de imagem</label><select value={resolution} onChange={e=>setResolution(e.target.value)}>
    <option value="kdp_300dpi">KDP — 300 DPI/PPI para imagens de impressão</option><option value="ebook_300ppi">eBook — 300 PPI no tamanho de exibição</option><option value="cover_2560x1600">Capa eBook — 2560 × 1600 px (ideal)</option><option value="cover_2500px">Capa eBook — pelo menos 2500 px de altura</option><option value="custom">Personalizada / gráfica</option>
   </select><small>Para impressão, a referência KDP é no mínimo 300 DPI. A capa de eBook tem requisitos próprios.</small></div>
  </div>}
  {tab==="ai"&&<div className="formCard">
   <div><label>Comando / esboço para a IA</label><textarea value={aiBrief} onChange={e=>setAiBrief(e.target.value)} placeholder="Ex.: Crie um livro infantil de 24 páginas sobre... personagens... faixa etária... estilo..."></textarea><small>Use como briefing principal da IA.</small></div>
   <div><label>Script / roteiro detalhado</label><textarea value={aiScript} onChange={e=>setAiScript(e.target.value)} placeholder="Cole aqui seu roteiro, estrutura, capítulos, cenas ou instruções página a página."></textarea><small>Quando preenchido, o gerador deve tratar este texto como instrução do projeto.</small></div>
  </div>}
  {tab==="author"&&<div className="formCard">
   <div><label>Autor / nome de publicação</label><input value={author} onChange={e=>setAuthor(e.target.value)} placeholder="Ex.: seu nome / nome artístico"/></div>
   <div><label>Uso do nome</label><p>Será usado na página de título, metadados e capa quando a etapa correspondente estiver configurada.</p></div>
  </div>}
 </div>
}

function PhotoDraft({files,setFiles,cover,setCover,back,setBack,interior,setInterior,printFiles,setPrintFiles,printCover,setPrintCover,printBack,setPrintBack,printInterior,setPrintInterior}:{files:File[];setFiles:(v:File[])=>void;cover:string|null;setCover:(v:string|null)=>void;back:string|null;setBack:(v:string|null)=>void;interior:string[];setInterior:(v:string[])=>void;printFiles:File[];setPrintFiles:(v:File[])=>void;printCover:string|null;setPrintCover:(v:string|null)=>void;printBack:string|null;setPrintBack:(v:string|null)=>void;printInterior:string[];setPrintInterior:(v:string[])=>void}){
 const [urls,setUrls]=useState<string[]>([]);
 useEffect(()=>{const next=files.map(f=>URL.createObjectURL(f));setUrls(next);return()=>next.forEach(URL.revokeObjectURL)},[files]);
 function add(e:React.ChangeEvent<HTMLInputElement>){
  const incoming=Array.from(e.target.files||[]);const valid=incoming.filter(f=>["image/jpeg","image/png","image/webp"].includes(f.type));
  if(files.length+valid.length>100){alert("O limite é de 100 fotos por projeto.");return}
  if(valid.length<incoming.length)alert("Algumas imagens foram ignoradas. Use JPG, PNG ou WEBP.");
  setFiles([...files,...valid]);e.target.value="";
 }
 function removePrint(i:number){
  setPrintFiles(printFiles.filter((_,n)=>n!==i));
  const shift=(v:string|null)=>v===null?null:(Number(v)===i?null:Number(v)>i?String(Number(v)-1):v);
  setPrintCover(shift(printCover)); setPrintBack(shift(printBack));
  setPrintInterior(printInterior.filter(x=>Number(x)!==i).map(x=>Number(x)>i?String(Number(x)-1):x));
 }
 function addPrint(e:React.ChangeEvent<HTMLInputElement>){
  const incoming=Array.from(e.target.files||[]);const valid=incoming.filter(f=>f.type==="application/pdf");
  if(printFiles.length+valid.length>100){alert("O limite é de 100 arquivos de impressão por projeto.");return}
  if(valid.length<incoming.length)alert("Alguns arquivos foram ignorados. Use PDF.");
  setPrintFiles([...printFiles,...valid]);e.target.value="";
 }
 function remove(i:number){setFiles(files.filter((_,n)=>n!==i));if(cover===String(i))setCover(null);else if(cover!==null&&Number(cover)>i)setCover(String(Number(cover)-1));if(back===String(i))setBack(null);else if(back!==null&&Number(back)>i)setBack(String(Number(back)-1));setInterior(interior.filter(x=>Number(x)!==i).map(x=>String(Number(x)>i?Number(x)-1:Number(x))));}
 function toggleInterior(i:number){const k=String(i);setInterior(interior.includes(k)?interior.filter(x=>x!==k):[...interior,k]);}
 return <div className="section"><div className="sectionTitle"><div><h3>Fotos pessoais</h3><p>Adicione até 100 fotos da galeria do celular ou do PC. A capa, contracapa e fotos do interior são escolhidas separadamente.</p></div><label className="primary small" style={{cursor:"pointer"}}>Adicionar fotos<input type="file" accept="image/jpeg,image/png,image/webp" multiple hidden onChange={add}/></label></div>
 {files.length===0?<div className="resultBox">Opcional: você pode criar o livro sem fotos. Se adicionar fotos, elas serão preparadas automaticamente sem esticar ou deformar a imagem.</div>:<div className="photoGrid">{files.map((f,i)=><div className="photoCard" key={i}><img src={urls[i]} alt={f.name}/><b>{f.name}</b><div className="photoActions"><button className={cover===String(i)?"primary small":"outline small"} onClick={()=>setCover(cover===String(i)?null:String(i))}>Capa</button><button className={back===String(i)?"primary small":"outline small"} onClick={()=>setBack(back===String(i)?null:String(i))}>Contracapa</button><button className={interior.includes(String(i))?"primary small":"outline small"} onClick={()=>toggleInterior(i)}>Interior</button><button className="outline small danger" onClick={()=>remove(i)}>Excluir</button></div></div>)}</div>}
 <small>{files.length}/100 fotos preparadas • {cover!==null?"capa definida":"capa não definida"} • {back!==null?"contracapa definida":"contracapa não definida"} • {interior.length} no interior</small>
 <div className="sectionTitle" style={{marginTop:22}}><div><h3>PDFs e arquivos montados</h3><p>Adicione somente PDFs já montados. As fotos são adicionadas exclusivamente na seção acima para evitar duplicidade.</p></div><label className="primary small" style={{cursor:"pointer"}}>Adicionar PDFs<input type="file" accept=".pdf,application/pdf" multiple hidden onChange={addPrint}/></label></div>
 {printFiles.length===0?<div className="resultBox">Opcional: nenhum PDF montado adicionado. As fotos ficam exclusivamente na seção acima.</div>:<div className="printFileList">{printFiles.map((f,i)=><div className="printFileRow" key={i}><div className="projectIcon"><Printer/></div><div className="projectInfo"><b>{i+1}. {f.name}</b><span>{(f.size/1024/1024).toFixed(1)} MB • {printCover===String(i)?"Capa":printBack===String(i)?"Contracapa":printInterior.includes(String(i))?"Interior":"Sem função"}</span></div><button className={printCover===String(i)?"primary small":"outline small"} onClick={()=>{setPrintCover(printCover===String(i)?null:String(i));setPrintBack(printBack===String(i)?null:printBack);}}>Capa</button><button className={printBack===String(i)?"primary small":"outline small"} onClick={()=>{setPrintBack(printBack===String(i)?null:String(i));setPrintCover(printCover===String(i)?null:printCover);}}>Contracapa</button><button className={printInterior.includes(String(i))?"primary small":"outline small"} onClick={()=>setPrintInterior(printInterior.includes(String(i))?printInterior.filter(x=>x!==String(i)):[...printInterior,String(i)])}>Interior</button><button className="outline small danger" onClick={()=>removePrint(i)}>Excluir</button></div>)}</div>}
 <small>{printFiles.length}/100 arquivos PDF/impressão serão enviados junto com o projeto.</small></div>
}

function Workspace({project,onBack,onProjectUpdate,aiPrompt,setAiPrompt,aiResult,generate,goVideo,goPrint}:{project:Project|null;onBack:()=>void;onProjectUpdate:(id:string)=>Promise<void>;aiPrompt:string;setAiPrompt:(v:string)=>void;aiResult:string;generate:()=>void;goVideo:()=>void;goPrint:()=>void}){
 const stageNames=["Briefing","Estrutura","Manuscrito","Revisão","Imagens","Layout","Capa","Validação","Exportação"];
 const stageKeys=["brief","outline","manuscript","revision","assets","layout","cover","validation","export"];
 const [done,setDone]=useState<boolean[]>(()=>stageNames.map((_,i)=>(project?.progress||0)>=[10,20,35,45,55,65,80,90,100][i]));
 const [busy,setBusy]=useState<number|null>(null),[stageMsg,setStageMsg]=useState("");
 useEffect(()=>setDone(stageNames.map((_,i)=>(project?.progress||0)>=[10,20,35,45,55,65,80,90,100][i])),[project?.id,project?.progress]);
 async function runStage(i:number){
  if(!project)return;
  setBusy(i);setStageMsg("Executando "+stageNames[i]+"...");
  try{
   const r=await fetch(API+"/api/projects/"+project.id+"/stage/"+stageKeys[i],{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({})});
   const d=await r.json();if(!r.ok)throw new Error(d.detail||"Falha na etapa.");
   setDone(x=>x.map((v,j)=>j<=i?true:v));await onProjectUpdate(project.id);setStageMsg(stageNames[i]+" concluída.");
  }catch(e){setStageMsg(e instanceof Error?e.message:"Falha na etapa.");}
  finally{setBusy(null)}
 }
 return <section className="page">
  <div className="sectionTitle"><div><h3>{project?.name||"Projeto"}</h3><small>{project?.book_type} • {project?.language}</small></div><div className="actions"><button className="outline small" onClick={goPrint}><Printer/> Preparar impressão</button><button className="outline small" onClick={goVideo}><Video/> Criar vídeo</button><button className="outline small" onClick={onBack}>Voltar</button></div></div>
  <div className="grid"><Feature icon={<FileText/>} title="Manuscrito" text="Estrutura, capítulos, revisão e tradução."/><Feature icon={<ImageIcon/>} title="Fotos pessoais" text="Até 100 fotos da galeria do PC ou celular, com capa, contracapa e interior."/><Feature icon={<Video/>} title="Vídeo social" text="Roteiro e geração de vídeo para divulgação."/><Feature icon={<ShieldCheck/>} title="Validação" text="Relatório antes da exportação."/></div>\n  <PhotoLibrary project={project}/>
  <div className="section"><div className="sectionTitle"><div><h3>Produção em 9 etapas</h3><p>Execute cada etapa na ordem. O projeto salva checkpoint após cada conclusão.</p></div><span>{done.filter(Boolean).length}/9 concluídas</span></div>
   <div className="projects">{stageNames.map((name,i)=>{const locked=i>0&&!done[i-1];return <div className="project" key={stageKeys[i]}><div className="projectIcon">{done[i]?<CheckCircle2/>:i+1}</div><div className="projectInfo"><b>{name}</b><span>{done[i]?"Concluída":locked?"Bloqueada até concluir a etapa anterior":"Pronta para execução"}</span><div className="bar"><i style={{width:(done[i]?100:0)+"%"}}/></div></div><button className={done[i]?"outline small":"primary small"} disabled={busy!==null||locked} onClick={()=>runStage(i)}>{busy===i?<RefreshCw/>:done[i]?"Executar novamente":locked?"Bloqueada":"Executar"}</button></div>})}</div>
   {stageMsg&&<div className="resultBox">{stageMsg}</div>}
  </div>
  <div className="section"><h3>Saída KDP</h3><p>Depois da validação, a exportação gera o miolo no formato selecionado. A capa completa permanece separada: contracapa + lombada + frente.</p><div className="actions"><button className="outline" onClick={()=>runStage(8)} disabled={busy!==null}><FileText/> Exportar PDF</button><button className="primary" onClick={()=>runStage(6)} disabled={busy!==null}><ImageIcon/> Gerar capa</button></div></div>
  <div className="section"><h3>Assistente de texto</h3><p>Use suas APIs configuradas. O roteador prioriza nuvem/API e deixa a IA local como fallback.</p><div className="formCard"><div><label>Prompt</label><input value={aiPrompt} onChange={e=>setAiPrompt(e.target.value)} placeholder="Ex.: crie o briefing deste livro..."/></div><div><button className="primary" onClick={generate}><Sparkles/> Gerar</button></div></div>{aiResult&&<div className="resultBox">{aiResult}</div>}</div>
 </section>
}

function PhotoLibrary({project}:{project:Project|null}){
 const [photos,setPhotos]=useState<any[]>([]),[cover,setCover]=useState<string|null>(null),[back,setBack]=useState<string|null>(null),[interior,setInterior]=useState<string[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 async function load(){if(!project)return;try{const r=await fetch(API+"/api/projects/"+project.id+"/photos");const d=await r.json();setPhotos(d.photos||[]);setCover(d.cover||null);setBack(d.back_cover||null);setInterior(d.interior||[])}catch{}}
 useEffect(()=>{load()},[project?.id]);
 async function upload(e:React.ChangeEvent<HTMLInputElement>){if(!project||!e.target.files?.length)return;const selected=Array.from(e.target.files);if(photos.length+selected.length>100){setMsg("O limite é de 100 fotos por projeto.");return}const fd=new FormData();selected.forEach(f=>fd.append("files",f));setBusy(true);setMsg("Importando fotos...");try{const r=await fetch(API+"/api/projects/"+project.id+"/photos",{method:"POST",body:fd});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Falha ao importar fotos");setMsg(d.added.length+" foto(s) adicionada(s).");await load()}catch(e){setMsg(e instanceof Error?e.message:"Falha ao importar fotos.")}finally{setBusy(false);e.target.value=""}}
 async function saveRoles(next:any){if(!project)return;setCover(next.cover);setBack(next.back_cover);setInterior(next.interior);try{await fetch(API+"/api/projects/"+project.id+"/photos",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});setMsg("Função das fotos salva.")}catch{setMsg("Não foi possível salvar a seleção.")}}
 function toggle(id:string){setInterior(x=>x.includes(id)?x.filter(v=>v!==id):x.length<100?[...x,id]:x)}
 return <div className="section"><div className="sectionTitle"><div><h3>Fotos pessoais</h3><p>Até 100 fotos. No celular, escolha diretamente da galeria; no PC, da pasta de imagens.</p></div><label className="primary small" style={{cursor:"pointer"}}>{busy?"Importando...":"Adicionar fotos"}<input type="file" accept="image/jpeg,image/png,image/webp" multiple hidden onChange={upload} disabled={busy||photos.length>=100}/></label></div>
 {photos.length===0?<div className="resultBox">Nenhuma foto adicionada ainda. Você poderá definir uma foto separadamente para capa, contracapa e escolher as fotos internas.</div>:<div className="photoGrid">{photos.map(p=><div className="photoCard" key={p.id}><img src={API+"/api/projects/"+project?.id+"/photos/"+p.id} alt={p.name}/><b>{p.name}</b><div className="photoActions"><button className={cover===p.id?"primary small":"outline small"} onClick={()=>saveRoles({cover:p.id,back_cover:back,interior})}>Capa</button><button className={back===p.id?"primary small":"outline small"} onClick={()=>saveRoles({cover,back_cover:p.id,interior})}>Contracapa</button><button className={interior.includes(p.id)?"primary small":"outline small"} onClick={()=>{const next=interior.includes(p.id)?interior.filter(v=>v!==p.id):[...interior,p.id];saveRoles({cover,back_cover:back,interior:next})}}>Interior</button></div></div>)}</div>}
 <small>{photos.length}/100 fotos usadas • {interior.length} selecionadas para o interior{msg?" • "+msg:""}</small></div>
}

function PrintStudio({project,onBack}:{project:Project|null;onBack:()=>void}){
 const [files,setFiles]=useState<any[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[download,setDownload]=useState<string|null>(null),[downloadName,setDownloadName]=useState("");
 const [paper,setPaper]=useState("A4"),[orientation,setOrientation]=useState("portrait"),[fit,setFit]=useState("contain"),[margin,setMargin]=useState("5"),[gray,setGray]=useState(false),[name,setName]=useState("material_para_impressao"),[cw,setCw]=useState("210"),[ch,setCh]=useState("297"),[outputFormat,setOutputFormat]=useState("pdf"),[printMode,setPrintMode]=useState("kdp"),[showOtherFormats,setShowOtherFormats]=useState(false);
 async function load(){if(!project)return;try{const [r,p]=await Promise.all([fetch(API+"/api/projects/"+project.id+"/print-files"),fetch(API+"/api/projects/"+project.id)]);const d=await r.json();const pd=await p.json();setFiles(d.files||[]);setPrintMode(pd?.spec?.print_mode==="independent_print"||pd?.spec?.publication_format==="independent_print"?"independent_print":"kdp");}catch{}}\n async function changePrintMode(v:string){if(!project)return;setPrintMode(v);try{const r=await fetch(API+"/api/projects/"+project.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({spec:{...((await (await fetch(API+"/api/projects/"+project.id)).json()).spec||{}),print_mode:v,publication_format:v==="independent_print"?"independent_print":"paperback"}})});if(!r.ok)throw new Error("Não foi possível salvar o modo de impressão.");setMsg(v==="independent_print"?"Modo independente / gráfica ativado.":"Modo KDP Amazon ativado.");}catch(e){setMsg(e instanceof Error?e.message:"Não foi possível salvar o modo de impressão.");}}
 useEffect(()=>{load()},[project?.id]);
 useEffect(()=>{if(printMode!=="independent_print"){setOutputFormat("pdf");setShowOtherFormats(false)}},[printMode]);
 async function add(e:React.ChangeEvent<HTMLInputElement>){if(!project||!e.target.files?.length)return;const selected=Array.from(e.target.files);if(files.length+selected.length>100){setMsg("O limite é de 100 arquivos por projeto.");return}const fd=new FormData();selected.forEach(f=>fd.append("files",f));setBusy(true);setMsg("Importando arquivos...");try{const r=await fetch(API+"/api/projects/"+project.id+"/print-files",{method:"POST",body:fd});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Falha ao importar.");setFiles(d.files||[]);setMsg("Arquivos importados.");}catch(err){setMsg(err instanceof Error?err.message:"Falha ao importar")}finally{setBusy(false);e.target.value=""}}
 async function setRole(id:string,role:string){if(!project)return;try{const r=await fetch(API+"/api/projects/"+project.id+"/print-files/role",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,role})});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Falha ao definir função.");setFiles(d.files||[])}catch(err){setMsg(err instanceof Error?err.message:"Falha ao definir função.")}}
 async function remove(id:string){if(!project)return;try{const r=await fetch(API+"/api/projects/"+project.id+"/print-files/"+id,{method:"DELETE"});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Falha.");setFiles(d.files||[])}catch(err){setMsg(err instanceof Error?err.message:"Falha ao excluir.")}}
 async function move(index:number,delta:number){if(!project)return;const next=[...files];const to=index+delta;if(to<0||to>=next.length)return;[next[index],next[to]]=[next[to],next[index]];setFiles(next);try{const r=await fetch(API+"/api/projects/"+project.id+"/print-files/order",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids:next.map(x=>x.id)})});if(!r.ok)throw new Error("Falha ao salvar a ordem.");}catch(err){setMsg(err instanceof Error?err.message:"Falha ao ordenar.")}}
 async function build(fmt=outputFormat){if(!project||!files.length)return;setBusy(true);setDownload(null);setDownloadName("");setMsg("Preparando arquivo para impressão...");
  try{const r=await fetch(API+"/api/projects/"+project.id+"/print-files/build",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({paper_size:paper,orientation,fit,margin_mm:Number(margin)||0,grayscale:gray,name,custom_width_mm:Number(cw)||210,custom_height_mm:Number(ch)||297,output_format:fmt})});
   const d=await r.json();if(!r.ok)throw new Error(d.detail||"Falha ao montar o arquivo.");
   setDownload(API+"/api/projects/"+project.id+"/print-files/download/"+encodeURIComponent(d.filename));setDownloadName(d.filename||"arquivo_para_impressao");setMsg("Arquivo pronto. A proporção foi preservada e a medida escolhida foi aplicada.");
  }catch(err){setMsg(err instanceof Error?err.message:"Falha ao montar o arquivo.")}finally{setBusy(false)}
 }
 if(!project)return <section className="page"><div className="empty"><Printer/><b>Selecione um projeto primeiro.</b><button className="outline" onClick={onBack}>Voltar</button></div></section>;
 const independent=printMode==="independent_print";
 return <section className="page"><div className="sectionTitle"><div><h3>Preparar arquivos para impressão</h3><p>{independent?"Modo independente / gráfica: use a medida exata solicitada pela gráfica, preserve a proporção e escolha a saída final.":"Organize PDFs e gere um arquivo de impressão conforme o modo definido no projeto."}</p></div><button className="outline small" onClick={onBack}>Voltar</button></div>
 <div className="formCard"><div><label>Modo de produção</label><select value={printMode} onChange={e=>changePrintMode(e.target.value)}><option value="kdp">KDP Amazon</option><option value="independent_print">Impressão independente / gráfica</option></select><small>Você pode trocar o modo aqui mesmo, inclusive em projetos já criados.</small></div><div><label>Arquivos</label><label className="primary small" style={{cursor:"pointer",width:"fit-content"}}>Adicionar PDF / imagens<input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,application/pdf,image/jpeg,image/png,image/webp" multiple hidden onChange={add}/></label><small>Até 100 arquivos por projeto. A proporção original é preservada; o sistema não estica nem achata as páginas.</small></div><div><b>{files.length}/100 arquivos</b><p>PDFs e imagens podem ser organizados, definidos como capa, contracapa ou interior.</p></div></div>
 {files.length?<div className="printFileList">{files.map((f,i)=><div className="printFileRow" key={f.id}><div className="projectIcon"><Printer/></div><div className="projectInfo"><b>{i+1}. {f.name}</b><span>{f.path} • {f.role||"Interior"}</span></div><button className={f.role==="cover"?"primary small":"outline small"} onClick={()=>setRole(f.id,"cover")}>Capa</button><button className={f.role==="back_cover"?"primary small":"outline small"} onClick={()=>setRole(f.id,"back_cover")}>Contracapa</button><button className={f.role==="interior"||!f.role?"primary small":"outline small"} onClick={()=>setRole(f.id,"interior")}>Interior</button><button className="outline small" disabled={i===0} onClick={()=>move(i,-1)}><ArrowUp/></button><button className="outline small" disabled={i===files.length-1} onClick={()=>move(i,1)}><ArrowDown/></button><button className="outline small danger" onClick={()=>remove(f.id)}>Excluir</button></div>)}</div>:<div className="resultBox">Adicione os arquivos que você tem autorização para imprimir. O sistema aplicará o tamanho escolhido sem distorcer a proporção.</div>}
 <div className="formCard"><div><label>Tamanho do papel</label><select value={paper} onChange={e=>setPaper(e.target.value)}><option value="A4">A4 — 210 × 297 mm</option><option value="A5">A5 — 148 × 210 mm</option><option value="LETTER">Carta — 216 × 279 mm</option><option value="LEGAL">Legal — 216 × 356 mm</option><option value="OFICIO">Ofício — 216 × 330 mm</option><option value="CUSTOM">Personalizado — medida da gráfica</option></select><label>Orientação</label><select value={orientation} onChange={e=>setOrientation(e.target.value)}><option value="portrait">Retrato</option><option value="landscape">Paisagem</option></select><label>Ajuste da página</label><select value={fit} onChange={e=>setFit(e.target.value)}><option value="contain">Encaixar sem cortar — recomendado</option><option value="cover">Preencher página — pode cortar bordas</option></select></div><div><label>Margem</label><input type="number" min="0" max="100" step="0.5" value={margin} onChange={e=>setMargin(e.target.value)}/><small>Milímetros. Use a medida de sangria/margem informada pela gráfica.</small><label>Cor</label><select value={gray?"gray":"color"} onChange={e=>setGray(e.target.value==="gray")}><option value="color">Colorido</option><option value="gray">Preto e branco / escala de cinza</option></select><label>Modo de produção</label><div className="resultBox" style={{margin:"6px 0"}}><b>{independent?"Impressão independente / gráfica":"KDP Amazon"}</b><br/><small>{independent?"Medidas personalizadas, sem distorção e com escolha do formato de saída.":"Saída de impressão seguindo o modo KDP configurado no projeto."}</small></div>{independent&&<><button className="outline" type="button" onClick={()=>setShowOtherFormats(v=>!v)}>{showOtherFormats?"Ocultar outros formatos":"Outros formatos de arquivo"}</button>{showOtherFormats&&<div className="formCard" style={{marginTop:10}}><div><label>Escolha como deseja salvar</label><select value={outputFormat} onChange={e=>setOutputFormat(e.target.value)}><option value="pdf">PDF — pronto para impressão</option><option value="png">PNG — imagens em alta qualidade (ZIP)</option><option value="jpg">JPG — imagens em alta qualidade (ZIP)</option><option value="tiff">TIFF — imagens para gráfica (ZIP)</option></select><small>Para gráfica, confirme previamente se ela exige PDF ou imagens em TIFF/JPG/PNG.</small></div></div>}</>}<label>Nome do arquivo final</label><input value={name} onChange={e=>setName(e.target.value)}/></div></div>
 {paper==="CUSTOM"&&<div className="formCard"><div><label>Largura personalizada (mm)</label><input type="number" min="1" value={cw} onChange={e=>setCw(e.target.value)}/><small>Informe exatamente a largura solicitada pela gráfica.</small></div><div><label>Altura personalizada (mm)</label><input type="number" min="1" value={ch} onChange={e=>setCh(e.target.value)}/><small>Informe exatamente a altura solicitada pela gráfica.</small></div></div>}
 <div className="actions"><button className="primary" disabled={!files.length||busy} onClick={()=>build(outputFormat)}>{busy?"Processando...":independent&&outputFormat!=="pdf"?"Gerar "+outputFormat.toUpperCase()+" para gráfica":"Gerar PDF pronto para impressão"}<Printer/></button></div>{download&&<div className="resultBox"><b>Arquivo criado com sucesso.</b><br/><a className="primary small" href={download} target="_blank" rel="noreferrer" style={{marginTop:10}}>Abrir / baixar {downloadName||"arquivo"}</a><br/><small>O arquivo usa a medida escolhida, preserva a proporção e fica disponível para conferência antes de enviar à gráfica.</small></div>}{msg&&<div className="resultBox">{msg}</div>}</section>
}

function AffiliatePanel(){
 const [base,setBase]=useState(""),[token,setToken]=useState(localStorage.getItem("kdp:affiliateToken")||""),[dash,setDash]=useState<any>(null),[mode,setMode]=useState<"login"|"register">("login"),[form,setForm]=useState({name:"",email:"",wallet:"",pin:""}),[msg,setMsg]=useState("");
 useEffect(()=>{fetch(API+"/api/affiliate/config").then(r=>r.json()).then(d=>setBase(d.api_base)).catch(()=>{})},[]);
 async function call(path:string,options:any={}){const headers={...(options.headers||{}),"Content-Type":"application/json"};if(token)headers.Authorization="Bearer "+token;const r=await fetch(base+path,{...options,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||"Erro no programa de afiliados");return d}
 async function login(){try{const d=await call("/affiliate/login",{method:"POST",body:JSON.stringify({email:form.email,pin:form.pin})});localStorage.setItem("kdp:affiliateToken",d.session_token);setToken(d.session_token);setDash(d);setMsg("Login realizado.")}catch(e){setMsg(e instanceof Error?e.message:"Falha no login.")}}
 async function register(){try{const d=await call("/affiliate/register",{method:"POST",body:JSON.stringify(form)});setMsg("Cadastro criado. Seu código é "+d.code+". Agora entre com e-mail e PIN.");setMode("login")}catch(e){setMsg(e instanceof Error?e.message:"Falha no cadastro.")}}
 async function load(){try{const d=await call("/affiliate/api/me");setDash(d)}catch{localStorage.removeItem("kdp:affiliateToken");setToken("");setDash(null)}}
 useEffect(()=>{if(token&&base)load()},[base]);
 async function wallet(){try{const d=await call("/affiliate/api/profile",{method:"POST",body:JSON.stringify({wallet:form.wallet})});setDash(d);setMsg("Carteira atualizada.")}catch(e){setMsg(e instanceof Error?e.message:"Falha.")}}
 function logout(){localStorage.removeItem("kdp:affiliateToken");setToken("");setDash(null)}
 if(dash)return <section className="page"><div className="sectionTitle"><div><h3>Meu painel de afiliado</h3><small>Venda o KDP AI Factory mesmo sem ativar sua licença de cliente.</small></div><button className="outline small" onClick={logout}><LogOut/> Sair</button></div><div className="grid"><Feature icon={<Users/>} title="Código" text={dash.code}/><Feature icon={<Activity/>} title="Clientes no mês" text={String(dash.clients_this_month)}/><Feature icon={<Sparkles/>} title="Comissão do mês" text={"US$ "+Number(dash.commission_month_usd).toFixed(2)}/><Feature icon={<ShieldCheck/>} title="Saldo disponível" text={"US$ "+Number(dash.available_usd).toFixed(2)}/></div><div className="formCard"><div><b>Seu link de indicação</b><p className="mono">{base+"/r/"+dash.code}</p></div><button className="outline" onClick={()=>navigator.clipboard?.writeText(base+"/r/"+dash.code)}><Copy/> Copiar link</button></div><div className="formCard"><div><label>Carteira BSC para receber</label><input value={form.wallet||dash.wallet||""} onChange={e=>setForm({...form,wallet:e.target.value})}/></div><button className="primary" onClick={wallet}>Salvar carteira</button></div><div className="section"><h3>Como funciona</h3><p>Compartilhe seu link. Quando uma venda válida for atribuída ao seu código, a comissão aparece no painel. O controle administrativo de pagamentos permanece no servidor.</p><p><b>Faixas atuais:</b> {dash.tiers}</p></div></section>;
 return <section className="page"><div className="sectionTitle"><div><h3>Programa de afiliados</h3><small>Disponível independentemente da licença do aplicativo.</small></div></div><div className="formCard"><div><label>Nome</label><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><label>E-mail</label><input value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/>{mode==="register"&&<><label>Carteira BSC</label><input value={form.wallet} onChange={e=>setForm({...form,wallet:e.target.value})}/></>}<label>PIN</label><input type="password" value={form.pin} onChange={e=>setForm({...form,pin:e.target.value})}/></div><button className="primary" onClick={mode==="login"?login:register}>{mode==="login"?<><LogIn/> Entrar</>:<><Users/> Cadastrar</>}</button></div><div className="actions"><button className="outline" onClick={()=>setMode(mode==="login"?"register":"login")}>{mode==="login"?"Quero ser afiliado":"Já sou afiliado"}</button></div>{msg&&<div className="resultBox">{msg}</div>}</section>
}

function VideoStudio({projects,project,onSelect,onBack,onConfigure}:{projects:Project[];project:Project|null;onSelect:(p:Project)=>void;onBack:()=>void;onConfigure:()=>void}){
 const [providers,setProviders]=useState<Provider[]>([]),[provider,setProvider]=useState(""),[prompt,setPrompt]=useState(""),[duration,setDuration]=useState("15"),[ratio,setRatio]=useState("9:16"),[resolution,setResolution]=useState("1080p"),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch(API+"/api/video-providers").then(r=>r.json()).then(d=>{setProviders(d);if(d[0])setProvider(d[0].id)}).catch(()=>{})},[]);
 async function generate(){if(!project||!provider)return;setBusy(true);setResult(null);try{const r=await fetch(API+"/api/projects/"+project.id+"/video",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({provider_id:provider,prompt,duration:Number(duration),aspect_ratio:ratio,resolution})});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Falha ao gerar vídeo");setResult(d)}catch(e){setResult({error:e instanceof Error?e.message:"Falha ao gerar vídeo"})}finally{setBusy(false)}}
 return <section className="page"><div className="sectionTitle"><div><h3>Gerador de vídeos</h3><small>Escolha um projeto já criado e use a sua própria API de vídeo configurada neste PC.</small></div><button className="outline small" onClick={onBack}>Voltar</button></div>
 <div className="formCard"><div><label>📚 Projeto / livro que será transformado em vídeo</label><select value={project?.id||""} onChange={e=>{const p=projects.find(x=>x.id===e.target.value);if(p){onSelect(p);setResult(null)}}}><option value="">Selecione um projeto</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name} • {p.book_type} • {p.language}</option>)}</select>{project&&<small>Projeto selecionado: <b>{project.name}</b>. O conteúdo e os dados do projeto serão usados como base para o roteiro.</small>}</div></div>
 {project?<div className="videoLayout"><div className="formCard"><div><label>🤖 API de vídeo</label><select value={provider} onChange={e=>setProvider(e.target.value)}><option value="">Selecione uma API cadastrada</option>{providers.map(p=><option key={p.id} value={p.id}>{p.name} • {p.model||"modelo"}</option>)}</select><small>A chave pertence ao usuário e fica armazenada localmente neste computador.</small><label>Roteiro / instrução adicional</label><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Deixe vazio para o Factory montar um roteiro baseado no livro."/><label>Duração</label><select value={duration} onChange={e=>setDuration(e.target.value)}><option value="10">10 segundos</option><option value="15">15 segundos</option><option value="30">30 segundos</option><option value="60">60 segundos</option></select><label>Formato</label><select value={ratio} onChange={e=>setRatio(e.target.value)}><option value="9:16">9:16 — Reels/TikTok/Shorts</option><option value="1:1">1:1 — Feed</option><option value="16:9">16:9 — YouTube</option></select><label>Resolução</label><select value={resolution} onChange={e=>setResolution(e.target.value)}><option>720p</option><option>1080p</option><option>4K</option></select></div><button className="primary" disabled={!provider||busy} onClick={generate}>{busy?<><RefreshCw/> Gerando...</>:<><Play/> Gerar vídeo</>}</button></div><div className="videoPreview"><Video size={54}/><b>Prévia / resultado</b>{result?<pre>{JSON.stringify(result,null,2)}</pre>:<span>O resultado da API aparecerá aqui e será salvo no projeto.</span>}</div></div>:<div className="empty"><BookOpen/><b>Selecione um projeto para começar.</b><span>Os livros são criados e revisados normalmente. O vídeo é uma etapa separada, depois do projeto estar pronto para divulgação.</span></div>}
 <div className="formCard"><div><b>🔑 Configurar minha API de vídeo</b><p>Cadastre sua própria chave em <b>Sistema / IA → Vídeo</b>. O KDP AI Factory não fornece nem paga a API de vídeo.</p></div><button className="outline" onClick={onConfigure}>Configurar APIs</button></div></section>}

function System({system,license,onActivated}:{system:any;license:any;onActivated:()=>void}){
 const [token,setToken]=useState(""),[tx,setTx]=useState(""),[asset,setAsset]=useState("USDT"),[referral,setReferral]=useState(localStorage.getItem("kdp:referralCode")||""),[msg,setMsg]=useState(""),[intent,setIntent]=useState<any>(null),[hardware,setHardware]=useState<any>(null),[aiProviders,setAiProviders]=useState<Provider[]>([]),[engine,setEngine]=useState({url:"",token:"",configured:false}),[aiTab,setAiTab]=useState<"all"|"text"|"image"|"video">("all");
 const blank={name:"",kind:"text",base_url:"",endpoint:"/v1/chat/completions",api_key:"",model:"",priority:100};const [provider,setProvider]=useState<any>(blank);
 async function loadConfig(){try{const [h,a,e]=await Promise.all([fetch(API+"/api/hardware"),fetch(API+"/api/ai/providers"),fetch(API+"/api/engine")]);setHardware(await h.json());setAiProviders(await a.json());setEngine({...engine,...await e.json(),token:""})}catch{}}
 useEffect(()=>{loadConfig()},[]);
 async function newPaymentIntent(nextAsset:string){setMsg("Gerando pedido protegido...");try{const r=await fetch(API+"/api/license/payment-intent",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({asset:nextAsset})});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Não foi possível criar o pedido.");setIntent(d);setMsg(`Pedido criado. Envie exatamente ${d.expected_amount} ${nextAsset} pela BNB Smart Chain e depois informe o TXID.`)}catch(e){setIntent(null);setMsg(e instanceof Error?e.message:"Falha ao criar pedido.")}}
 useEffect(()=>{newPaymentIntent(asset)},[asset]);
 async function saveAI(){setMsg("Salvando API...");try{const r=await fetch(API+"/api/ai/providers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(provider)});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Não foi possível salvar.");setAiProviders(x=>[...x.filter(p=>p.id!==d.id),d].sort((a,b)=>(a.priority??100)-(b.priority??100)));setProvider({...blank,kind:provider.kind,endpoint:provider.kind==="video"||provider.kind==="image"?"/v1/"+provider.kind+"s/generations":"/v1/chat/completions"});setMsg("API salva com proteção local da chave.");}catch(e){setMsg(e instanceof Error?e.message:"Falha ao salvar API.")}}
 async function del(id:string){if(!confirm("Excluir esta API?"))return;await fetch(API+"/api/ai/providers/"+id,{method:"DELETE"});setAiProviders(x=>x.filter(p=>p.id!==id))}
 async function test(id:string){setMsg("Testando...");try{const r=await fetch(API+"/api/ai/providers/test",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({provider_id:id})});const d=await r.json();setMsg(r.ok?d.message:"Erro: "+(d.detail||"falha"))}catch(e){setMsg("Falha no teste.")}}
 async function saveEngine(){try{const r=await fetch(API+"/api/engine",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url:engine.url,token:engine.token})});const d=await r.json();setEngine({...engine,configured:d.configured,token:""});setMsg("Engine remoto salvo.")}catch(e){setMsg("Falha ao salvar engine.")}}
 const filtered=useMemo(()=>aiTab==="all"?aiProviders:aiProviders.filter(p=>p.kind===aiTab||p.kind==="all"||(aiTab==="text"&&p.kind==="both")||(aiTab==="image"&&p.kind==="both")),[aiProviders,aiTab]);
 async function activate(){try{const r=await fetch(API+"/api/license/activate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({license_token:token.trim()})});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Licença inválida.");setMsg("Licença ativada.");setToken("");onActivated()}catch(e){setMsg(e instanceof Error?e.message:"Falha ao ativar.")}}
 async function pay(){if(!intent){setMsg("Crie o pedido protegido antes de pagar.");return}try{const r=await fetch(API+"/api/license/payment",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tx_id:tx.trim(),asset,referral_code:referral.trim(),intent_id:intent.intent_id,intent_secret:intent.intent_secret})});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Pagamento não validado.");setMsg("Pagamento confirmado e licença vinculada ao usuário/dispositivo.");setTx("");setIntent(null);onActivated()}catch(e){setMsg(e instanceof Error?e.message:"Falha ao verificar.")}}
 return <section className="page"><div className="sectionTitle"><h3>Sistema, hardware e IA</h3><span>{system?"Online":"Sem conexão"}</span></div>
 <div className="grid"><Feature icon={<Activity/>} title="Hardware" text={hardware?hardware.tier+" • "+hardware.ram_gb+" GB RAM":"Detectando..."}/><Feature icon={<Cloud/>} title="Cloud-first" text="APIs remotas são priorizadas para manter o PC leve."/><Feature icon={<Video/>} title="Vídeo" text="Provedores de vídeo cadastrados no mesmo gerenciador."/><Feature icon={<ShieldCheck/>} title="Persistência" text="Configurações e projetos sobrevivem ao fechamento do app."/></div>
 <div className="section"><div className="sectionTitle"><div><h3>Gerenciador de APIs de IA</h3><p>Não existem duas caixas fixas. Você pode cadastrar <b>quantas APIs quiser</b>.</p></div><span><Save/> Salvamento permanente</span></div>
 <div className="tabs">{[["all","Todas"],["text","Texto"],["image","Imagem"],["video","Vídeo"]].map(([k,l])=><button className={aiTab===k?"tab active":"tab"} key={k} onClick={()=>setAiTab(k as any)}>{l}</button>)}</div>
 <div className="providerList">{filtered.map(p=><div className="providerRow" key={p.id}><div className="providerBadge">{p.kind==="video"?<Video/>:p.kind==="image"?<ImageIcon/>:<Brain/>}</div><div className="providerInfo"><b>{p.name}</b><span>{p.kind} • {p.model||"modelo automático"} • prioridade {p.priority??100} • {p.key_configured?"chave configurada":"sem chave"}</span></div><button className="outline small" onClick={()=>test(p.id)}><CheckCircle2/> Testar</button><button className="outline small danger" onClick={()=>del(p.id)}><Trash2/></button></div>)}{!filtered.length&&<div className="empty"><Brain/><b>Nenhuma API nesta categoria.</b><span>Use o formulário abaixo para adicionar a primeira.</span></div>}</div>
 <div className="formCard"><div><label>Nome da API / provedor</label><input value={provider.name} onChange={e=>setProvider({...provider,name:e.target.value})} placeholder="Ex.: DeepSeek, Qwen, API de vídeo..."/><label>Tipo de capacidade</label><select value={provider.kind} onChange={e=>setProvider({...provider,kind:e.target.value,endpoint:e.target.value==="video"?"/v1/videos/generations":e.target.value==="image"?"/v1/images/generations":"/v1/chat/completions"})}><option value="text">Texto</option><option value="image">Imagem</option><option value="video">Vídeo</option><option value="both">Texto + imagem</option><option value="all">Texto + imagem + vídeo</option></select><label>Base URL</label><input value={provider.base_url} onChange={e=>setProvider({...provider,base_url:e.target.value})} placeholder="https://api.exemplo.com"/><label>Endpoint</label><input value={provider.endpoint} onChange={e=>setProvider({...provider,endpoint:e.target.value})}/><label>API Key</label><input type="password" value={provider.api_key} onChange={e=>setProvider({...provider,api_key:e.target.value})} placeholder="Cole sua chave; ela fica protegida localmente"/><label>Modelo</label><input value={provider.model} onChange={e=>setProvider({...provider,model:e.target.value})} placeholder="nome-do-modelo"/><label>Prioridade (1 = primeiro)</label><input type="number" value={provider.priority} onChange={e=>setProvider({...provider,priority:Number(e.target.value)||100})}/></div><button className="primary" disabled={!provider.name||!provider.base_url} onClick={saveAI}><Plus/> Adicionar API</button></div>
 </div>
 <div className="section"><h3>Engine GPU remoto</h3><p>Para IA pesada, conecte uma VPS/engine. O aplicativo permanece leve e usa o remoto antes do local.</p><div className="formCard"><div><label>URL HTTPS</label><input value={engine.url} onChange={e=>setEngine({...engine,url:e.target.value})} placeholder="https://ai.seudominio.com"/><label>Token</label><input type="password" value={engine.token} onChange={e=>setEngine({...engine,token:e.target.value})}/><small>{engine.configured?"Configurado":"Não configurado"}</small></div><button className="primary" disabled={!engine.url} onClick={saveEngine}>Salvar engine</button></div></div>
 <div className="formCard"><div><b>Ativar licença existente</b><p>Cole o token recebido do servidor oficial.</p><input value={token} onChange={e=>setToken(e.target.value)} placeholder="KDP1...."/></div><button className="primary" disabled={!token.trim()} onClick={activate}>Ativar licença</button></div>
 <div className="formCard"><div><b>Comprar licença vitalícia — US$50</b><p>Pagamento em BNB ou USDT na BNB Smart Chain.</p>{intent&&<p><b>Valor exato deste pedido: {intent.expected_amount} {asset}</b><br/><small>Esse valor é exclusivo do seu pedido. O TXID público, sozinho, não libera a licença.</small></p>}<input value={tx} onChange={e=>setTx(e.target.value)} placeholder="TXID da transação"/><input value={referral} onChange={e=>{setReferral(e.target.value.toUpperCase());localStorage.setItem("kdp:referralCode",e.target.value.toUpperCase())}} placeholder="Código do afiliado (opcional)"/><select value={asset} onChange={e=>{setAsset(e.target.value);setTx("");}}><option>USDT</option><option>BNB</option></select></div><button className="primary" disabled={!tx.trim()||!intent} onClick={pay}>Verificar pagamento</button></div>
 {msg&&<div className="resultBox">{msg}</div>}</section>
}

function Feature({icon,title,text}:{icon:any;title:string;text:string}){return <div className="feature">{icon}<div><b>{title}</b><p>{text}</p></div></div>}
function Projects({items,onOpen}:{items:Project[];onOpen:(p:Project)=>void}){if(!items.length)return <div className="empty"><CheckCircle2/><b>Seu primeiro livro começa aqui.</b><span>Crie um projeto e o Factory cuidará do restante.</span></div>;return <div className="projects">{items.map(p=><button className="project" key={p.id} onClick={()=>onOpen(p)}><div className="projectIcon">📘</div><div className="projectInfo"><b>{p.name}</b><span>{p.book_type} • {p.language}</span><div className="bar"><i style={{width:p.progress+"%"}}/></div></div><strong>{p.progress}%</strong></button>)}</div>}
