import {useEffect,useState} from "react";
import {BookOpen,Brain,CheckCircle2,ChevronRight,FileText,Image as ImageIcon,Library,Plus,Settings,ShieldCheck,Sparkles,WandSparkles,Activity,Box,Upload,Download} from "lucide-react";
const API="http://127.0.0.1:8000";
type Project={id:string;name:string;book_type:string;language:string;status:string;progress:number};
const types=[["childrens","🎨","Livro infantil","Histórias, personagens e ilustrações"],["fiction","📖","Romance / Ficção","Livros longos com capítulos"],["educational","📚","Educativo","Conteúdo didático"],["workbook","📝","Workbook","Exercícios e atividades"],["journal","📓","Diário / Journal","Diários e planners"],["cookbook","🍳","Livro de receitas","Receitas e conteúdo culinário"],["study","🧠","Estudo / Apostila","Resumos e questões"],["coloring","🖍️","Colorir / Atividades","Páginas para colorir"],["poetry","✒️","Poesia","Poemas e coletâneas"],["notebook","📒","Caderno","Miolo simples"],["custom","⚙️","Personalizado","Projeto livre"]];
const stages=["brief","outline","manuscript","revision","assets","layout","cover","validation","export"];
export default function App(){
 const [projects,setProjects]=useState<Project[]>([]),[name,setName]=useState(""),[type,setType]=useState("childrens"),[language,setLanguage]=useState("pt-BR"),[loading,setLoading]=useState(false),[view,setView]=useState("home"),[system,setSystem]=useState<any>(null),[selected,setSelected]=useState<Project|null>(null),[aiPrompt,setAiPrompt]=useState(""),[aiResult,setAiResult]=useState("");
 async function load(){try{const [p,d]=await Promise.all([fetch(API+"/api/projects"),fetch(API+"/api/doctor")]);setProjects(await p.json());setSystem(await d.json())}catch{}}
 useEffect(()=>{load()},[]);
 async function create(){if(!name.trim())return;setLoading(true);try{const r=await fetch(API+"/api/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,book_type:type,language})});const p=await r.json();setProjects(x=>[p,...x]);setName("");setSelected(p);setView("workspace")}finally{setLoading(false)}}
 async function generate(){if(!aiPrompt)return;setAiResult("Gerando...");try{const r=await fetch(API+"/api/ai/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:aiPrompt})});const d=await r.json();setAiResult(d.text||d.detail||"Sem resposta")}catch(e){setAiResult("Não foi possível conectar ao Ollama.")}}
 return <div className="app"><aside className="sidebar"><div className="brand"><div className="logo">K</div><div><b>KDP AI</b><span>FACTORY</span></div></div><nav>
 <button className={view==="home"?"active":""} onClick={()=>setView("home")}><Sparkles/>Início</button>
 <button className={view==="projects"?"active":""} onClick={()=>setView("projects")}><Library/>Meus projetos</button>
 <button className={view==="new"?"active":""} onClick={()=>setView("new")}><Plus/>Novo livro</button>
 <button className={view==="system"?"active":""} onClick={()=>setView("system")}><Activity/>Sistema / IA</button>
 </nav><div className="sideBottom"><div className="miniStatus"><span className="dot"/>{system?"Sistema local online":"Conectando..."}<br/><small>Sem créditos obrigatórios</small></div><button onClick={()=>setView("system")}><Settings/>Configurações</button></div></aside>
 <main><header><div><span className="eyebrow">LOCAL-FIRST • OPEN-SOURCE STACK</span><h1>{view==="new"?"Criar novo livro":view==="projects"?"Meus projetos":view==="workspace"?"Área de produção":view==="system"?"Sistema e modelos":"Sua fábrica editorial com IA"}</h1></div><button className="outline" onClick={()=>setView("new")}><Plus/> Novo projeto</button></header>
 {view==="home"&&<><section className="hero"><div><div className="pill"><WandSparkles/> IA local • sem créditos obrigatórios</div><h2>Transforme uma ideia em um <em>livro completo.</em></h2><p>Escreva, ilustre, diagrama, valide e prepare seus livros para KDP em um único ambiente.</p><button className="primary" onClick={()=>setView("new")}>Começar um livro <ChevronRight/></button></div><div className="heroArt"><BookOpen size={110}/><Sparkles className="spark s1"/><Sparkles className="spark s2"/></div></section>
 <section className="grid"><Feature icon={<Brain/>} title="IA local" text="Ollama e modelos locais, sem API paga obrigatória."/><Feature icon={<ImageIcon/>} title="Imagens" text="ComfyUI com workflows reutilizáveis."/><Feature icon={<ShieldCheck/>} title="Validação KDP" text="Verificação de especificação e PDF."/><Feature icon={<Upload/>} title="Importação" text="PDF, DOCX, EPUB, TXT, MD, CSV e PPTX."/></section>
 <section className="section"><div className="sectionTitle"><h3>Projetos recentes</h3><button onClick={()=>setView("projects")}>Ver todos</button></div><Projects items={projects.slice(0,4)} onOpen={p=>{setSelected(p);setView("workspace")}}/></section></>}
 {view==="projects"&&<section className="section page"><div className="sectionTitle"><h3>{projects.length?projects.length+" projeto(s)":"Nenhum projeto ainda"}</h3><button className="primary small" onClick={()=>setView("new")}><Plus/> Criar livro</button></div><Projects items={projects} onOpen={p=>{setSelected(p);setView("workspace")}}/></section>}
 {view==="new"&&<section className="creator"><div className="step"><span>01</span><div><b>Escolha o tipo de livro</b><small>Você poderá ajustar a especificação depois.</small></div></div><div className="typeGrid">{types.map(t=><button className={type===t[0]?"type selected":"type"} onClick={()=>setType(t[0])} key={t[0]}><span className="typeIcon">{t[1]}</span><strong>{t[2]}</strong><small>{t[3]}</small></button>)}</div><div className="formCard"><div><label>Nome do projeto</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: A Floresta Encantada"/></div><div><label>Idioma</label><select value={language} onChange={e=>setLanguage(e.target.value)}><option value="pt-BR">Português (Brasil)</option><option value="en-US">English (US)</option><option value="es-ES">Español</option><option value="fr-FR">Français</option><option value="de-DE">Deutsch</option></select></div></div><div className="actions"><button className="outline" onClick={()=>setView("home")}>Cancelar</button><button className="primary" disabled={!name.trim()||loading} onClick={create}>{loading?"Criando...":"Criar projeto"}<ChevronRight/></button></div></section>}
 {view==="workspace"&&<Workspace project={selected} onBack={()=>setView("projects")} aiPrompt={aiPrompt} setAiPrompt={setAiPrompt} aiResult={aiResult} generate={generate}/>}
 {view==="system"&&<System system={system}/>}
 </main></div>
}
function Workspace({project,onBack,aiPrompt,setAiPrompt,aiResult,generate}:{project:Project|null;onBack:()=>void;aiPrompt:string;setAiPrompt:(v:string)=>void;aiResult:string;generate:()=>void}){return <section className="page"><div className="sectionTitle"><div><h3>{project?.name||"Projeto"}</h3><small>{project?.book_type} • {project?.language}</small></div><button className="outline small" onClick={onBack}>Voltar</button></div><div className="grid"><Feature icon={<FileText/>} title="Manuscrito" text="Estrutura, capítulos, revisão e tradução."/><Feature icon={<ImageIcon/>} title="Assets" text="Imagens e catálogo de recursos."/><Feature icon={<Box/>} title="Diagramação" text="PDF, DOCX e EPUB."/><Feature icon={<ShieldCheck/>} title="Validação" text="Relatório antes da exportação."/></div><div className="section"><h3>Pipeline editorial</h3><div className="projects">{stages.map((s,i)=><div className="project" key={s}><div className="projectIcon">{i+1}</div><div className="projectInfo"><b>{s}</b><span>{i===0?"Briefing":i===1?"Estrutura":i===2?"Manuscrito":i===3?"Revisão":i===4?"Imagens":i===5?"Layout":i===6?"Capa":i===7?"Validação":"Exportação"}</span><div className="bar"><i style={{width:(i===0?100:0)+"%"}}/></div></div></div>)}</div></div><div className="section"><h3>Assistente local</h3><p>Use o modelo instalado no Ollama para rascunhar ideias, capítulos ou revisões.</p><div className="formCard"><div><label>Prompt</label><input value={aiPrompt} onChange={e=>setAiPrompt(e.target.value)} placeholder="Ex.: crie o briefing deste livro..."/></div><div><button className="primary" onClick={generate}><Sparkles/> Gerar</button></div></div>{aiResult&&<div className="page" style={{marginTop:12,whiteSpace:"pre-wrap"}}>{aiResult}</div>}</div></section>}
function System({system}:{system:any}){return <section className="page"><div className="sectionTitle"><h3>Diagnóstico local</h3><span>{system?"Disponível":"Sem conexão"}</span></div><div className="grid"><Feature icon={<Activity/>} title="API" text={system?"Respondendo":"Não detectada"}/><Feature icon={<Brain/>} title="Ollama" text="Verifique modelos na CLI: kdp-factory models"/><Feature icon={<ImageIcon/>} title="ComfyUI" text="Workflow JSON pode ser conectado ao gerador."/><Feature icon={<Download/>} title="Modelos" text="A instalação de pesos é sempre explícita pelo usuário."/></div><pre style={{background:"#10141b",color:"#e9edf2",padding:18,borderRadius:12,overflow:"auto"}}>{JSON.stringify(system,null,2)}</pre></section>}
function Feature({icon,title,text}:{icon:any;title:string;text:string}){return <div className="feature">{icon}<div><b>{title}</b><p>{text}</p></div></div>}
function Projects({items,onOpen}:{items:Project[];onOpen:(p:Project)=>void}){if(!items.length)return <div className="empty"><CheckCircle2/><b>Seu primeiro livro começa aqui.</b><span>Crie um projeto e o Factory cuidará do restante.</span></div>;return <div className="projects">{items.map(p=><button className="project" key={p.id} onClick={()=>onOpen(p)}><div className="projectIcon">📘</div><div className="projectInfo"><b>{p.name}</b><span>{p.book_type} • {p.language}</span><div className="bar"><i style={{width:p.progress+"%"}}/></div></div><strong>{p.progress}%</strong></button>)}</div>}
